### ISSUE TITLE
README example throwing "methods.parse is not a function"

### ISSUE THREAD

**Issue by mx781** [spencermountain/dumpster-dip#1]
Hey @spencermountain major kudos to this suite of wikidump parsing tools! 

I'm getting this when running the provided example:
```javascript
TypeError [Error]: methods.parse is not a function
    at eachPage (file:///opt/projects/foo/node_modules/dumpster-dip/src/worker/index.js:52:21)
    at SundayDriver.each (file:///opt/projects/foo/node_modules/dumpster-dip/src/worker/01-reader.js:18:7)
    at SundayDriver.doChunk (/opt/projects/foo/node_modules/sunday-driver/src/index.js:38:8)
    at doit (/opt/projects/foo/node_modules/sunday-driver/src/index.js:77:10)
    at SundayDriver.onData (/opt/projects/foo/node_modules/sunday-driver/src/index.js:87:3)
    at ReadStream.<anonymous> (/opt/projects/foo/node_modules/sunday-driver/src/02-start.js:15:10)
    at ReadStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
```

I tried pinning wtf to 10.0.0 as in package.json but still a no-go. The code I'm running is verbatim from the example in the README, bar an actual file path. I'm using the Slovenian wiki dump as a testbed (`slwiki-20230120-pages-articles-multistream.xml`) Any ideas?

**Comment by spencermountain** [comment]
hey @mx781 - yeah, if you pass in a `parse` method, it should go-through. That seems funny.
```js
dip({ input:'/path/to', parse: (doc) => {    }})
```
I'm not actually sure what that multistream file is - i usually use the `wiki-latest-pages-articles.xml.bz2` - do you know what the difference is?

i can help if you're stuck, but take a look at [the workerData props](https://github.com/spencermountain/dumpster-dip/blob/main/src/pool/Pool.js#L33) - they get passed-in pretty straightforwardly.
cheers

**Comment by mx781** [comment]
Thanks for replying so quickly! the multistream is just their recommended version so that some xml parsers can read starting from different parts of the file (better for parallelization and if you want to extract a doc that's later in the file).

The issue went away after I dropped the arrow syntax in favour of the good ol' `function(blah){}` - unsure whether this was to do with JSONfn, the way I was running it (vanilla node via command-line invocation), my node version (v18.15.0) or something silly (probably this) - didn't have time to dig into it
