### ISSUE TITLE
Question about Wiki Talk, Wikinews, Wikibooks, etc.

### ISSUE THREAD

**Issue by shayne-longpre** [spencermountain/dumpster-dip#5]
Hello @spencermountain thank you for this awesome work!

We're hoping to process Wikinews, Wikibooks, Wikitravel/Wikivoyage, and the Wiki talk files as well. Does your code support that, or just the main wikipedia pages?

Thank you!

**Comment by spencermountain** [comment]
Hey Shayne, yep I think all mediawiki dumps will work in principle. I know others have used it with wikibooks and wikinews, so it's worth a shot. 

There may be some unsupported templates here and there, but I'm happy to help play whackamole, if you find anything missing 
Cheers

**Comment by shayne-longpre** [comment]
Thanks Spencer!

For context, we're trying to process all the wiki sources using your tool. It looks like the [Talk pages](https://meta.wikimedia.org/wiki/Talk:Data_dumps) are embedded in `pages-meta-current` xml dumps. Would your tool provide a way to separate out the articles from the talk pages portions?

Also, as a starter I tried running your tool on `dvwiki-latest-pages-articles.xml` (a small language) but hit this error:

```
file:///Users/shayne/Documents/research/node_modules/dumpster-dip/src/pool/Pool.js:75
      let row = this.status.map(o => o.written.toLocaleString().padStart('8')).join('   ')
                                               ^

TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at file:///Users/shayne/Documents/research/node_modules/dumpster-dip/src/pool/Pool.js:75:48
    at Array.map (<anonymous>)
    at Timeout._onTimeout (file:///Users/shayne/Documents/research/node_modules/dumpster-dip/src/pool/Pool.js:75:29)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.10.0
```

**Comment by spencermountain** [comment]
Hey Shayne, yep for the talk pages, you'll need to download the larger dump,  `-latest-pages-meta-current.xml.bz2` instead of `-latest-pages-articles.xml`. The format of the dump is the same, and both files should work.
To process only the talk pages, add `namespace: 1` to your config.

I've got a new release nearly ready, and hope to publish it either tomorrow or on friday. This should help with the above issue, and I will let you know when it's released.
cheers

**Comment by spencermountain** [comment]
just released `2.0.0` - please check it out.
Also includes a runnable [talk-page example](https://github.com/spencermountain/dumpster-dip/blob/main/examples/talk-pages/run.js) that worked for me.
cheers
